name: Claude PR Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  issues:
    types: [assigned]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  claude:
    if: contains(github.event.comment.body, '@claude') || contains(github.event.issue.body, '@claude') || contains(github.event.review.body, '@claude')
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Claude Code Action
        uses: anthropics/claude-code-action@v1
        with:
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          # anthropic-oauth-token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}  # Alternative to API key